#!/bin/bash

echo "enter the age"
read age
if [[ age < 13 ]]; then 
	echo "child"
elif [[ age > 13 || age < 19 ]]; then
	echo "teenager"
elif [[ age > 20 ]] ; then
	echo "adult"
elif [[ age > 60 ]] ; then
	echo "oldage"
else 
	echo "NA"
fi

